Camel 15211 ssl context params configuration
apache/camel pull request #11812
Opened 2023-10-23 11:24 UTC by jono-morris

Added  `camel.main.ssl.` parameters allowing Camel's SSL security parameters to be configured.

Tests added to camel-jetty, camel-netty, and camel-vertx.

2023-10-23 11:41 UTC, oscerd approved these changes

2023-10-23 12:38 UTC, davsclaus requested changes
Add a new camel.main.xxx - should also update in PrepareCamelMainMojo and there is also code changes needed in BaseMainSupport

2023-10-23 12:38 UTC, davsclaus commented on core/camel-main/src/main/java/org/apache/camel/main/DefaultConfigurationProperties.java
> +    private String sslKeystorePassword = "changeit";
We should not have default passwords

2023-10-24 12:07 UTC, jono-morris commented
Thanks for the review.  Give me a day to make the changes.

2023-10-26 11:45 UTC, jono-morris commented
Added camel.main.ssl.xxx, and updated PrepareCamelMainMojo and BaseMainSupport. 
Thanks.

2023-10-26 12:04 UTC, davsclaus commented
Can we change `camel.main.ssl` to `camel.ssl` as this is not tied to main only.

2023-10-26 12:50 UTC, jono-morris commented
Yes of course. Let me do that.

2023-10-27 10:12 UTC, jono-morris commented
Changes committed changing `camel.main.ssl` to `camel.ssl`.  Thanks

2023-10-27 11:00 UTC, davsclaus approved these changes

2023-10-27 11:02 UTC, davsclaus commented
We also need some work for camel-spring-boot, to make camel.ssl configuration possible via its auto configuration.

Its something like threadpool but not exactly the same, but you can take a look
https://github.com/apache/camel-spring-boot/tree/main/core/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/threadpool

2023-10-27 11:44 UTC, merged

2023-10-27 11:58 UTC, jono-morris commented
Yes certainly, let me take a look.