Replaced the Thread.sleep with the best option or removed it.
apache/camel pull request #11945
Opened 2023-11-08 23:33 UTC by rafamqrs

# Description

Replaced Thread.sleep() in camel-jms.

# Target

- [X] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [X] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [X] I checked that each commit in the pull request has a meaningful subject line and body.

- [X] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

2023-11-09 05:35 UTC, oscerd approved these changes
cc @orpiske

2023-11-09 08:44 UTC, orpiske commented
Thanks for the contribution! I'll be looking closely at this one later today ... currently busy with a CI issue.

2023-11-09 08:44 UTC, orpiske requested changes
Just marking like this 'cause it's pending further review.

2023-11-09 10:04 UTC, orpiske requested changes
Thanks for your contribution!

There are few places where I think it would be better to retain the `Thread.sleep` because the proposed solution with Awaitility makes the code harder to read (and, also, the adequate solution would be to reword the tests so that we can use adequate synchronization mechanisms - but that's beyond the point of this change).

Also, one more note about the commit message. Please make sure to write the commit message according to our standards. Trying doing something like this: 

```
CAMEL-19526: replaced the thread.sleep with the best option or removed
```

2023-11-09 10:04 UTC, orpiske commented on components/camel-jms/src/test/java/org/apache/camel/component/jms/async/MyAsyncProducer.java
> +                    .until(() -> true);
I think Thread.sleep is fine here.

2023-11-09 10:04 UTC, orpiske commented on components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/TempReplyToIssueTest.java
> +                .until(() -> true);
I think `Thread.sleep` is fine here.

2023-11-09 10:04 UTC, orpiske commented on components/camel-jms/src/test/java/org/apache/camel/component/jms/temp/JmsReconnectManualTest.java
> +                .until(() -> true);
I think `Thread.sleep` is fine here.

2023-11-09 22:14 UTC, rafamqrs commented on components/camel-jms/src/test/java/org/apache/camel/component/jms/temp/JmsReconnectManualTest.java
> +                .until(() -> true);
Makes Sense, thank you!

2023-11-09 22:16 UTC, rafamqrs commented
> Thanks for your contribution!
> 
> There are few places where I think it would be better to retain the `Thread.sleep` because the proposed solution with Awaitility makes the code harder to read (and, also, the adequate solution would be to refactor the tests so that we can use adequate synchronization mechanisms - but that's beyond the point of this change).
> 
> Also, one more note about the commit message. Please make sure to write the commit message according to our standards. Trying doing something like this:
> 
> ```
> CAMEL-19526: replaced the thread.sleep with the best option or removed
> ```

My bad, I ended up forgetting to write the Jira task on the commit message and keep the commit message according to the standards.

2023-11-10 09:25 UTC, orpiske approved these changes
Thanks for the contribution! LGTM

2023-11-10 09:25 UTC, merged