CAMEL-20103: fix the currency problem acquiring a producer template from the Defau…
apache/camel pull request #11971
Opened 2023-11-11 10:24 UTC by pnowak85

…ltProducerCache which can lead to a wrong producer being returned under high load

# Description

see [CAMEL-20103](https://issues.apache.org/jira/browse/CAMEL-20103)

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

2023-11-11 10:34 UTC, orpiske requested changes
Thanks for the contribution. 

Looking good, but marking as request changes because I'll review it more carefully on Monday.

2023-11-11 11:12 UTC, oscerd approved these changes

2023-11-13 13:18 UTC, orpiske commented
Finally, looking at this one ... 

I'll test it manually on my CI, but I am not initially concerned with the fix. It should be fine, I think.

2023-11-13 19:47 UTC, davsclaus approved these changes

2023-11-14 07:45 UTC, davsclaus commented
@orpiske did you finish your local CI test

2023-11-14 08:18 UTC, orpiske commented
Not yet ... the progress is slow due to maintenance on the lab. It should be finished soon.

2023-11-14 09:09 UTC, orpiske approved these changes
Finally completed. No issues with the patch ... let's merge.

2023-11-14 09:10 UTC, merged

2023-11-14 09:14 UTC, orpiske commented
We'll need to backport this to 4.0.3