Adding Jenkins file for PPC64LE JDK11
apache/camel pull request #12675
Opened 2024-01-05 12:24 UTC by sanskruti1098

Hi @oscerd to enable JDK11 jobs for power for camel- 3.x request to review and merge it

2024-01-05 12:43 UTC, orpiske requested changes
I'm not entirely sure what this is about, so marking as request changes until @oscerd is back from PTO.

2024-01-08 05:39 UTC, oscerd commented
Camel 3 will be EOL soon. I would probably focus on 3.x or 3.22.x, btw I'll merge it later in the week

2024-01-08 05:40 UTC, oscerd approved these changes

2024-01-08 09:44 UTC, merged

2024-01-08 09:52 UTC, oscerd commented
https://ci-builds.apache.org/job/Camel/job/Camel%20Build%203.21.x%20(ppc64le)/job/camel-3.21.x/