CAMEL-20613: set AbstractCamelContext#endpointStrategies to ConcurrentHashSet
apache/camel pull request #13821
Opened 2024-04-16 22:47 UTC by bartoszpop

CAMEL-20613: set AbstractCamelContext#endpointStrategies to ConcurrentHashSet to prevent ConcurrentModificationException

# Description

If a thread iterates over the list of strategies while another thread adds a new strategy, ConcurrentModificationException is thrown. To fix this issue, AbstractCamelContext#endpointStrategies can be set to a thread-safe collection.

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

2024-04-17 05:57 UTC, oscerd requested changes
Let's see, I'm not sure is referenced only there.

2024-04-17 06:12 UTC, gnodet approved these changes

2024-04-17 22:45 UTC, bartoszpop commented
> Let's see, I'm not sure is referenced only there.

@oscerd can you please elaborate on your comment?

2024-04-18 04:18 UTC, oscerd commented
I just meant to say let's run a full build

2024-04-18 05:09 UTC, davsclaus approved these changes

2024-04-18 11:29 UTC, merged