[CAMEL-20728] add S3 multipart upload support for stream producer in camel-aws2-s3
apache/camel pull request #14062
Opened 2024-05-06 12:43 UTC by bonnetb

# Description

See: https://issues.apache.org/jira/browse/CAMEL-20728
This PR aims to provide camel-aws2s3 producer for support for multipart upload in combination with streaming mode. Actually, today's streaming mode agregates messages into S3 objects, but each object is sent as a whole, which can be an issue if it is huge (memory failure). This PR enables multipart (S3 API multipart) for each object upload.
multiPartUpload must be enabled, and partSize will specify chunk sizes.

2024-05-06 13:23 UTC, oscerd approved these changes

2024-05-06 13:23 UTC, oscerd commented
/component-test aws

2024-05-06 13:24 UTC, oscerd commented
@jono-morris can you have a look? You worked on the streaming upload s3 for a while and also in relation to multipart. Thanks.

2024-05-06 16:37 UTC, davsclaus requested changes

2024-05-06 16:37 UTC, davsclaus commented on components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/stream/AWS2S3StreamUploadProducer.java
> +            if (LOG.isInfoEnabled()) {
Change to DEBUG logging

2024-05-06 16:37 UTC, davsclaus commented on components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/stream/AWS2S3StreamUploadProducer.java
> +            LOG.error("Error completing multipart updload");
Change to WARN and we likely need to include the caused exception so the user has a chance to understand why it failed. Also adjust the message to say that the upload will be aborted.

2024-05-07 07:28 UTC, davsclaus approved these changes

2024-05-07 08:36 UTC, merged