CamelTestSupport: removal of wrong annotation + addition of method for @Override
apache/camel pull request #14178
Opened 2024-05-17 12:13 UTC by JiriOndrusek

fixes https://issues.apache.org/jira/browse/CAMEL-20784

I remoced the annotation (`CamelQuarkusTest`) which does not exist and I moved the validation into a protected method. Child class is able to override the behavior if needed.

# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

2024-05-17 12:16 UTC, JiriOndrusek commented
FYI @orpiske
Ideally I'd use 'claszz.isAssignableFrom(CamelQuarkusTestSupport.class' instead of moving the validation  into protected method. But because I can use only String name of the class, I'd need to find class by name and handle ClassNotFoundException. I see solution in the PR clearer for the users.
In case you disagree I'll refactor it differently.

2024-05-17 12:22 UTC, orpiske requested changes
So, I'd like us to start decoupling this class. 

I am sorry to say it, but this class is horribly tightly couple and full of problems (i.e.: like mixing up being both an JUnit 5 Extension as well as a test case in itself. 

So, because of that, I would like us to not add more methods to its interface and, instead, work to slowly migrate those away (while giving time for the community to update code). 

That's why I'd marking this as request changes.

2024-05-17 12:24 UTC, orpiske commented on components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelTestSupport.java
> +
This is the problematic part I talk about on my comment.

2024-05-31 11:59 UTC, orpiske commented
@JiriOndrusek I think we can close this one, right?

2024-06-06 06:22 UTC, closed without merging

2024-06-06 06:22 UTC, orpiske commented
This has become invalid in the context of CAMEL-20785 changes. Let's close it.