CAMEL-21082 - do not delete existing file sin target folder when
apache/camel pull request #15159
Opened 2024-08-14 13:17 UTC by apupier

creating a new Camel integration files with Camel JBang init

# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally from root folder and I have committed all auto-generated changes.

2024-08-16 04:25 UTC, orpiske approved these changes
LGTM, but probably would be good to get a feedback from @davsclaus tool (maybe the behavior has a reason?)

2024-08-16 07:00 UTC, apupier commented
updated branch to remove the `Important` note from the documentation

2024-08-16 07:31 UTC, davsclaus requested changes
see JIRA

2024-08-17 06:49 UTC, davsclaus approved these changes

2024-08-17 06:49 UTC, merged