CAMEL-15514: Add auto generation of operation IDs
apache/camel pull request #4175
Opened 2020-09-08 11:51 UTC by Sonicsupremacy

Since operationId is an optional parameter as defined by OpenApi 3 standard, I think that improving the component to be able to auto generate missing operationIds from operation path and http method would benefit users of camel-rest-openapi component.

2020-09-08 11:59 UTC, oscerd approved these changes
LGTM, since the original contributor is @ffang I'd like to have his feedback too

2020-09-08 19:36 UTC, davsclaus approved these changes

2020-09-09 05:47 UTC, davsclaus commented
I wonder if you can end up generate duplicates if that path doesnt take the base path into account eg

- user
     GET {id}
- order
      GET {id}

Where user and order are base path, and the the path is {id}, then you have 2 operations with get-id

it should be

get-user-id
get-order-id

And can the id use dash or underscore to seperate the words nicely, otherwise its generated as getid, getuserid etc

2020-09-09 05:48 UTC, davsclaus requested changes
See my previous comment

2020-09-09 08:39 UTC, Sonicsupremacy commented
Dashes are now used for separating words.

@davsclaus it should not be possible to generate duplicates. OpenApi standard states that all paths are relative to api server url and paths also can not be nested. That guarantees that there can be no duplicate paths. Any base paths are specified at the api server url level.

To expand on your example:
paths
- user
   GET {id}
- order
   GET {id}

would be defined in api specification as:
- /user/{id} and
- /order/{id}

2020-09-09 12:17 UTC, davsclaus approved these changes

2020-09-09 12:17 UTC, merged