CAMEL-15484 - UPDATE Documentation for Camel 3.x
apache/camel pull request #4375
Opened 2020-10-07 03:47 UTC by UdaykiranMarupati

Update documentation for camel 3.x related to attachments as there is no exchange.getIn().getAttachments() method anymore.

Fix for the Issue [CAMEL-15484](https://issues.apache.org/jira/browse/CAMEL-15484?filter=12348073)

2020-10-07 04:12 UTC, oscerd requested changes
This needs to be done in components folder, in src/main/docs of the mail component

2020-10-07 22:26 UTC, UdaykiranMarupati commented
> This needs to be done in components folder, in src/main/docs of the mail component

2020-10-07 22:28 UTC, UdaykiranMarupati commented
Modified the documentation under src/main/docs folder.

2020-10-08 06:51 UTC, oscerd approved these changes

2020-10-08 06:51 UTC, merged