CAMEL-16790 Pulsar consumer can use external thread pool to receive messages to fix uneven message distribution
apache/camel pull request #5872
Opened 2021-07-27 19:43 UTC by klevy-toast

- [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/main/CONTRIBUTING.md

I noticed a pulsar bug where a 2nd consumer on a shared subscription will not be able to process messages in a large backlog when it uses the `messageListener` interface. It is being patched in pulsar 2.9.0 (see https://github.com/apache/pulsar/issues/11008), but in the short-term it would be useful to have a way of consuming these messages in camel without relying on the `messageListener` interface. This PR adds an option to the pulsar component to use a threadpool that continuously receives and handles messages, which does distribute messages properly, as demonstrated by the new integration test.

2021-07-28 04:40 UTC, oscerd approved these changes

2021-07-28 04:46 UTC, davsclaus requested changes

2021-07-28 04:46 UTC, davsclaus commented on components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarConsumer.java
> +            ExecutorService executor = Executors.newFixedThreadPool(numThreads);
Use Camel's executor service API for this, see getExecutorServiceManager on CamelContext

2021-07-28 04:46 UTC, davsclaus commented on components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarConsumer.java
> +                            LOGGER.error("Encountered exception while receiving message", e);
Use getExceptionHandler to handle this exception.

Also you would need to catch Exception to have a general catch and handle to keep the thread up and running.

2021-07-28 04:46 UTC, davsclaus commented on components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarConsumer.java
> +                executor.submit(() -> {
Also it may be worth to move this into its own private inner class so it has a class name that makes stacktraces and logging/debugging easier.

2021-07-28 04:46 UTC, davsclaus commented on components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/utils/PulsarUtils.java
> +        for (ExecutorService executor : executors) {
Use Camel's ExecutorServiceManager which has API for stopping thread pools

2021-07-28 20:39 UTC, klevy-toast commented
Thanks for the comments @davsclaus, didn't know about Camel's ExecutorServiceManager. I think that I addressed everything.

2021-07-29 04:37 UTC, davsclaus approved these changes

2021-07-29 04:42 UTC, oscerd approved these changes

2021-07-29 05:46 UTC, merged