[DOCS] Update HTTP and Kafka components.
apache/camel pull request #7919
Opened 2022-06-28 14:23 UTC by mmajerni

2022-06-28 17:46 UTC, orpiske requested changes
Thanks for the contribution. Overall it LGTM, but there is a small typo in one of the corrections.

2022-06-28 17:46 UTC, orpiske commented on components/camel-kafka/src/main/docs/kafka-component.adoc
> +On startup, the instance subscribes to the topic, rewinds the offset to the beginning and rebuilding the cache to the latest state. The cache will not be considered warmed up until one poll of `pollD
I think this should be:

```On startup, the instance subscribes to the topic, rewinds the offset to the beginning and rebuilds the cache to the latest state.
```

2022-06-29 09:02 UTC, mmajerni commented on components/camel-kafka/src/main/docs/kafka-component.adoc
> +On startup, the instance subscribes to the topic, rewinds the offset to the beginning and rebuilding the cache to the latest state. The cache will not be considered warmed up until one poll of `pollD
Fixed. Thanks, I missed that.

2022-06-29 10:43 UTC, orpiske approved these changes
Thanks for your contribution!

2022-06-29 10:48 UTC, davsclaus approved these changes

2022-06-29 11:34 UTC, merged