CAMEL-18262 - Fixing the Template issue
apache/camel pull request #7995
Opened 2022-07-10 03:02 UTC by rhuan080

Signed-off-by: Rhuan Rocha <rhuan080@gmail.com>

- [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/main/CONTRIBUTING.md

2022-07-10 07:22 UTC, oscerd approved these changes

2022-07-11 07:48 UTC, essobedo commented
@rhuan080 Thx for the PR, just one remark, as you have a clear reproducer, would you mind adding a test to ensure that the problem is fixed and will not occur anymore?

2022-07-11 14:11 UTC, rhuan080 commented
Hi @essobedo the camel-model-core does not have a unit test. I have seen the tests are applied to components. Thus, I had doubts about providing unit tests here.

2022-07-12 08:21 UTC, zhfeng commented
@rhuan080 can you add a unit test at https://github.com/apache/camel/tree/main/core/camel-core/src/test/java/org/apache/camel/model

2022-07-12 14:54 UTC, rhuan080 commented
Sure! I`ll send a commit soon.

2022-07-12 14:57 UTC, zhfeng commented
Thanks @rhuan080 and that could be great!

2022-07-12 19:08 UTC, essobedo reviewed
Thx for the unit test. Just to be sure, What happens when you remove your changes, does the test fail as expected?

2022-07-12 19:08 UTC, essobedo commented on core/camel-core/src/test/java/org/apache/camel/model/RouteConfigurationOnExceptionTest.java
> +        //mockEndpoint.expectedBodiesReceived(testMsg);
I guess this can be removed

2022-07-12 20:30 UTC, essobedo commented
There are some checkstyle errors to fix:

```
[ERROR] /home/runner/work/camel/camel/core/camel-core/src/test/java/org/apache/camel/model/RouteConfigurationOnExceptionTest.java:1: Line does not match expected header line of '/*'. [Header]
[ERROR] /home/runner/work/camel/camel/core/camel-core/src/test/java/org/apache/camel/model/RouteConfigurationOnExceptionTest.java:13:1: Wrong order for 'java.net.ConnectException' import. [ImportOrder]
```

2022-07-12 22:33 UTC, rhuan080 commented on core/camel-core/src/test/java/org/apache/camel/model/RouteConfigurationOnExceptionTest.java
> +        //mockEndpoint.expectedBodiesReceived(testMsg);
Done!

2022-07-12 22:34 UTC, rhuan080 commented
Done!

2022-07-13 08:19 UTC, zhfeng commented
The stylecheck failure is related to `GoogleSecretManagerPropertiesFunction.java`. So I think this PR looks good.

2022-07-13 08:37 UTC, essobedo requested changes
The PR doesn't really fix the bug, please don't merge

2022-07-13 08:55 UTC, essobedo commented
The test case doesn't really prove that the bug is fixed.

Here is a good test case with normal route and route template:

```
class RouteConfigurationOnExceptionTest extends ContextTestSupport {

    @Override
    protected RouteBuilder[] createRouteBuilders() {
        return new RouteBuilder[] {
            new RouteBuilder() {
                @Override
                public void configure() {
                    routeTemplate("route-template")
                        .from("direct:start-template")
                        .routeConfigurationId("my-error-handler")
                        .throwException(RuntimeException.class, "Expected Error");
                }
            },
            new RouteBuilder() {
                @Override
                public void configure() {
                    TemplatedRouteBuilder.builder(context, "route-template")
                        .routeId("my-test-file-route")
                        .add();
                }
            },
            new RouteBuilder() {
                @Override
                public void configure() {
                    from("direct:start-normal")
                        .routeConfigurationId("my-error-handler")
                        .throwException(RuntimeException.class, "Expected Error");
                }
            },
            new RouteConfigurationBuilder() {
                @Override
                public void configuration() {
                    routeConfiguration("my-error-handler").onException(Exception.class).handled(true)
                        .transform(constant("Error Received"))
                        .to("mock:result");
                }
            }
        };
    }

    @Test
    void testRouteTemplateCanSupportRouteConfiguration() throws Exception {
        getMockEndpoint("mock:result").expectedMessageCount(1);
        getMockEndpoint("mock:result").expectedBodiesReceived("Error Received");
        template.sendBody("direct:start-template", "foo");
        assertMockEndpointsSatisfied();
    }

    @Test
    void testNormalRouteCanSupportRouteConfiguration() throws Exception {
        getMockEndpoint("mock:result").expectedMessageCount(1);
        getMockEndpoint("mock:result").expectedBodiesReceived("Error Received");
        template.sendBody("direct:start-normal", "foo");
        assertMockEndpointsSatisfied();
    }
}
```

You will see that the test with the route template fails and the other passes. After a quick investigation, the main additional problem seems to be the fact that the route is not prepared when registering it.

2022-07-13 14:27 UTC, rhuan080 commented
Hi @essobedo,

Actually, the tests work with the new code and doesn`t work with the old code. I think we have two problems here, the copy I have done is correct. However, the test works because it is calling the Advice.adviceWith. This code is passing on tests 

```
@Test
    void testRouteTemplateCanSupportRouteConfiguration() throws Exception {
        AdviceWith.adviceWith(context, "my-test-file-route", routeBuilder -> {
            
        });
        getMockEndpoint("mock:result").expectedMessageCount(1);
        getMockEndpoint("mock:result").expectedBodiesReceived("Error Received");
        template.sendBody("direct:start-template", "foo");
        assertMockEndpointsSatisfied();
    }
```

2022-07-13 14:38 UTC, essobedo commented
I believe that it works with the `AdviceWith.doAdviceWith` because in this case the route is properly prepared but please note that `AdviceWith.doAdviceWith` is only meant for testing purpose, we don't use it in production code so the code proposed in the new version of test case is more what we will do in practice.

2022-07-13 14:44 UTC, essobedo commented
In other words, if you compare how a normal route and a templated route are initialized, you should see that in case of a templated route, this method is never called https://github.com/apache/camel/blob/main/core/camel-core-model/src/main/java/org/apache/camel/model/RoutesDefinition.java#L233

2022-07-13 16:16 UTC, rhuan080 commented
Hi @essobedo,

I have used your unit test code! Thank you for helping me with this! I sent another commit fixing the template that does not prepare the RouteDefinition. Please, look at this and tell me what you think. The first commit is right, however, it really dons`t solves the issue totally. Now it is solving.

2022-07-13 16:33 UTC, essobedo requested changes
We are very close, one small comment

2022-07-13 16:33 UTC, essobedo commented on core/camel-core-engine/src/main/java/org/apache/camel/impl/DefaultModel.java
> +    private RoutesDefinition routeCollection = new RoutesDefinition();
It is not meant to be shared, I rather prefer that you create a new instance at each call instead.

2022-07-13 16:40 UTC, essobedo approved these changes
LGTM thx!

2022-07-14 04:41 UTC, zhfeng approved these changes

2022-07-25 15:00 UTC, davsclaus approved these changes

2022-07-25 15:00 UTC, merged

2022-07-25 15:02 UTC, davsclaus commented
Thanks for the PR - I would like to prepare the route before adding