[Camel 18327] updated updateTaskState resume logic to seek from the point that was last committed
apache/camel pull request #8391
Opened 2022-09-18 23:47 UTC by geekrupam

2022-09-19 16:46 UTC, orpiske commented
Hi, there's a compilation failure:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project camel-kafka: Compilation failure
[ERROR] /home/runner/work/camel/camel/components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java:[430,29] error: unclosed string literal
[ERROR] -> [Help 1]
```

2022-09-19 16:50 UTC, orpiske requested changes
Thanks for the PR.

The implementation is looking promising, but there are some style and compilation issues. They need to be fixed so the automated tests can run.

2022-09-19 16:50 UTC, orpiske commented on components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
> +import org.apache.camel.component.kafka.consumer.support.*;
This causes a violation of the checkstyle. The imports need to be explicit.

2022-09-19 16:51 UTC, orpiske commented on components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
> +        return kafkaConsumer."isRunAllowed() && !kafkaConsumer.isStoppingOrStopped();
This one is causing the compilation issue.

2022-09-20 08:00 UTC, orpiske commented
Attaching the last logs for your debugging. The problem seems to be caused by checkstyle failures. You can fix and verify those by running the following command: 

```
mvn -Pformat,fastinstall clean install && mvn -Psourcecheck
```
[test-logs(4).zip](https://github.com/apache/camel/files/9605357/test-logs.4.zip)
[checkstyle.log(2).zip](https://github.com/apache/camel/files/9605358/checkstyle.log.2.zip)

2022-10-04 03:04 UTC, geekrupam commented
I keep getting the below error  when I try to build locally:
 Rule 0: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
Detected Maven Version: 3.3.9 is not in the allowed range 3.5.0.

2022-10-04 04:40 UTC, oscerd commented
Use a newer maven version. I'm able to build with an old 3.6.3 version, my suggestion is using the latest >3.8

2022-10-06 03:02 UTC, geekrupam commented
> Thanks for the PR.
> 
> The implementation is looking promising, but there are some style and compilation issues. They need to be fixed so the automated tests can run.

resolved

2022-10-06 14:45 UTC, orpiske commented
> ❌ Finished component verification: **1 component(s) test failed** out of 1 component(s) tested

Current failures are caused by checkstyle issue (which is preventing the test execution). I attached the logs for your analysis and fix. 

[test-logs.zip](https://github.com/apache/camel/files/9725798/test-logs.zip)

2022-10-07 15:19 UTC, geekrupam commented
I am not sure what is failing, the builds and test are successful when I run them locally. Also, I tested using  below command as well: mvn -Pformat,fastinstall clean install && mvn -Psourcecheck

2022-10-07 15:33 UTC, orpiske commented on components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
> +                            + e.getMessage() + ". This exception is ignored.",
The format check may be complaining because of this line. If you look at it, you can see that it's different than the previous version.

2022-10-07 15:33 UTC, orpiske commented on components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
> +                + threadId + " to " + topic + " after " + max + " attempts (elapsed: " + time + ").";
The format check may be complaining because of this line. If you look at it, you can see that it's different than the previous version.

2022-10-07 15:33 UTC, orpiske commented on components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
> +                threadId + " to " + topic + " after " + max + " attempts (elapsed: " + time + ").";
The format check may be complaining because of this line. If you look at it, you can see that it's different than the previous version.

2022-10-07 15:39 UTC, orpiske commented
One additional note, is that the code is currently out of sync with main and cannot be merged: 

"This branch cannot be rebased due to conflicts" 

To solve that you need to rebase the code with the current changes on main. Something like this would work:

```
git checkout main 
git pull --rebase upstream main 
git checkout CAMEL-18327-Kafka_consumer_closes_when_it_is_paused
git rebase main
```

This would put your work branch `CAMEL-18327-Kafka_consumer_closes_when_it_is_paused` in sync with the latest changes from main. 

Obs.: please note that the name of the remote may be different on your system. You can check that with `git remote -v`.

2022-10-07 16:25 UTC, geekrupam commented
rebased and format changes reverted

2022-10-07 16:29 UTC, orpiske commented
Thanks @geekrupam, but the branch is still in conflict and github won't allow us to merge. I think at some point there may have been a merge commit involved (if you look at the list of changes on the commit page here, you'll see it is listing 472 commits).

2022-10-07 17:56 UTC, geekrupam commented
I created a new branch with another poll request

2022-10-08 05:54 UTC, orpiske commented
Closing. The other PR was merged. Thanks for your contribution @geekrupam

2022-10-08 05:54 UTC, closed without merging