Camel 18719 : camel-jbang - Adding the dependency of camel-quarkus-core creates two entries in exported POM.xml
apache/camel pull request #8717
Opened 2022-11-15 04:16 UTC by mrinalsharma

This pull request fixes [CAMEL-18719](https://issues.apache.org/jira/browse/CAMEL-18719)

- `dep = dep.substring(0, dep.lastIndexOf(","));` removed extra `,` that was causing an empty dependency in pom.xml
- quarkus-pom.tmpl already have camel-quarkus-core, camel-quarkus-platform-http, camel-quarkus-microprofile-health  included so there was no need to add it again if  dependency was passed as `--deps`

2022-11-16 06:00 UTC, oscerd approved these changes

2022-11-16 22:22 UTC, davsclaus commented on dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
> +            dep = dep.substring(0, dep.lastIndexOf(","));
What if there is no comma in dep, then indexOf returns -1 and substring will fail. I think we need to check if dep ends with comma we can avoid adding the comma

2022-11-19 16:25 UTC, davsclaus commented
@mrinalsharma do you have time to fix that last comment?

2022-11-19 17:35 UTC, mrinalsharma commented
> 

Sorry, got stuck in a personal issue. Will try to finish it today.

2022-11-19 21:00 UTC, davsclaus commented
@mrinalsharma no rush, we need this within 2 weeks before we cut the 3.20 release

2022-11-21 08:19 UTC, essobedo requested changes
Hi, thx for your contribution. Could you please rebase your branch or recreate it? Indeed your changes are drowned in the middle of many other changes that are not related which makes the PR very hard to review

2022-11-21 10:28 UTC, davsclaus commented
Ah yeah this PR seems wrong now, you can try to create a new clean PR with only your changes, and then close this

2022-11-21 15:34 UTC, mrinalsharma commented
created a new Pull request https://github.com/apache/camel/pull/8749

2022-11-21 15:35 UTC, closed without merging