CAMEL-19050: add DHIS2 component
apache/camel pull request #9349
Opened 2023-02-14 20:42 UTC by claudemamo

# Description

Add DHIS2 Camel Component.

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I formatted the code using `mvn -Pformat,fastinstall install && mvn -Psourcecheck`

2023-02-15 05:44 UTC, davsclaus commented
Thanks for the contribution. 

However all the source code must use the ASF license header. So either you need to change this in the PR or we cannot accept the PR to ASF.

Also it would be good to write a bit more in the .doc file what dhis2 is. Just a few lines to explain it to users that do not know.

2023-02-15 08:51 UTC, oscerd requested changes
The code needs to have the ASF License header in all the files.

2023-02-15 08:51 UTC, oscerd commented on components/camel-dhis2/LICENSE
> +Copyright (c) 2004-2022, University of Oslo
The code must be provided with an ASF License compliant license: https://www.apache.org/legal/resolved.html#category-a

As far as I see this project has been licensed as BSD 3-Clause

This copyright of University of Oslo shouldn't be there.

2023-02-15 08:51 UTC, oscerd commented on components/camel-dhis2/camel-dhis2-api/pom.xml
> +        <firstVersion>3.21.0</firstVersion>
This should be 4.0.0-SNAPSHOT

2023-02-16 14:01 UTC, oscerd commented on components/camel-dhis2/camel-dhis2-api/pom.xml
> +        <firstVersion>3.21.0</firstVersion>
In that case no, it should be 3.21.0, but only after 3.21.0 will be release, so for the moment it should be 4.0.0-SNAPSHOT, until we release

2023-02-22 13:36 UTC, oscerd approved these changes

2023-02-23 08:16 UTC, oscerd approved these changes
LGTM, I'll try to merge it this week.

2023-02-24 10:16 UTC, oscerd commented
Trying to merge this but it's failing with

[ERROR] Failed to execute goal on project camel-dhis2: Could not resolve dependencies for project org.apache.camel:camel-dhis2:jar:4.0.0-SNAPSHOT: Could not find artifact org.apache.camel:camel-dhis2-api:jar:javadoc:4.0.0-SNAPSHOT in apache-public (https://repository.apache.org/content/groups/public/)

2023-02-24 11:00 UTC, oscerd commented
I removed the javadoc camel-dhis2-api jar, tests were passing. Merged and pushed. Thanks

2023-02-24 11:00 UTC, closed without merging